#TASK 2 — Data Cleaning

##Loading Dataset

In [ ]:
import pandas as pd

# Load the dataset
df = pd.read_csv('/content/patient_feedback_raw_data.csv')

# Display the first few rows of the DataFrame
df.head()

,Theme,Feedback,Sentiment,Satisfaction,Readmission
0,discharge,Discharge instructions were very clear,1,4,1
1,communication,I felt the doctor used too much medical jargon,1,5,0
2,medication,I appreciated the reminders about my medicines,1,4,0
3,discharge,Instructions after discharge were not helpful,0,1,1
4,discharge,Instructions after discharge were not helpful,0,2,1

### 1. Check Missing Values

In [ ]:
# Check for missing values
print("Missing values before cleaning:")
print(df.isnull().sum())

Missing values before cleaning:
Theme           0
Feedback        0
Sentiment       0
Satisfaction    0
Readmission     0
dtype: int64

### 2. Remove Missing Rows (if any)

In [ ]:
# Remove rows with any missing values
df_cleaned = df.dropna()
print("\nMissing values after removing rows (should be 0):")
print(df_cleaned.isnull().sum())
print(f"Original rows: {len(df)}, Rows after dropping NA: {len(df_cleaned)}")

Missing values after removing rows (should be 0):
Theme           0
Feedback        0
Sentiment       0
Satisfaction    0
Readmission     0
dtype: int64
Original rows: 1000, Rows after dropping NA: 1000

### 3. Remove Duplicate Rows

In [ ]:
# Remove duplicate rows
df_cleaned = df_cleaned.drop_duplicates()
print(f"\nRows after dropping duplicates: {len(df_cleaned)}")

Rows after dropping duplicates: 95

### 4. Clean Text Column (Feedback)

In [ ]:
import re

# Function to clean text
def clean_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'[^a-z0-9\s]', '', text)  # Remove punctuation and special characters
    text = re.sub(r'\s+', ' ', text).strip()  # Remove extra spaces
    return text

# Apply text cleaning to the 'Feedback' column
df_cleaned['Feedback'] = df_cleaned['Feedback'].apply(clean_text)
print("\nFirst 5 cleaned feedback entries:")
print(df_cleaned['Feedback'].head())

First 5 cleaned feedback entries:
0            discharge instructions were very clear
1    i felt the doctor used too much medical jargon
2    i appreciated the reminders about my medicines
3     instructions after discharge were not helpful
4     instructions after discharge were not helpful
Name: Feedback, dtype: object

### 5. Saving Cleaned Dataset

In [ ]:
# Save the cleaned DataFrame to a new CSV file
df_cleaned.to_csv('patient_feedback_cleaned.csv', index=False)
print("\nCleaned dataset saved to 'patient_feedback_cleaned.csv'")

# Display the head of the cleaned dataframe
print("\nHead of the cleaned DataFrame:")
display(df_cleaned.head())

Cleaned dataset saved to 'patient_feedback_cleaned.csv'

Head of the cleaned DataFrame:

,Theme,Feedback,Sentiment,Satisfaction,Readmission
0,discharge,discharge instructions were very clear,1,4,1
1,communication,i felt the doctor used too much medical jargon,1,5,0
2,medication,i appreciated the reminders about my medicines,1,4,0
3,discharge,instructions after discharge were not helpful,0,1,1
4,discharge,instructions after discharge were not helpful,0,2,1